//! Invitation Manager — Creates and manages position invitations for candidates

use chrono::{Duration, Utc};
use genflow_receptors::{InviteStatus, PositionInvite};
use genflow_shared_infra::{
    db::{begin_organization_transaction, set_transaction_org_context},
    error::AppError,
};
use sqlx::{PgPool, Row};
use uuid::Uuid;

pub struct InvitationManager {
    pool: PgPool,
}

impl InvitationManager {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Create an invitation for a position
    pub async fn create_invitation(
        &self,
        position_id: Uuid,
        invited_by_rep_id: Uuid,
        email: Option<String>,
        phone: Option<String>,
    ) -> Result<PositionInvite, AppError> {
        let organization_id = self.position_organization_id(position_id).await?;
        let invite_id = Uuid::new_v4();
        let invite_code = PositionInvite::generate_code();
        let expires_at = Utc::now() + Duration::days(7);
        let mut tx = begin_organization_transaction(&self.pool, organization_id).await?;

        sqlx::query(
            "INSERT INTO position_invites (id, position_id, invited_by_rep_id, candidate_id, invite_code, email, phone, status, expires_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)"
        )
            .bind(invite_id)
            .bind(position_id)
            .bind(invited_by_rep_id)
            .bind(None::<Uuid>) // candidate_id — to be filled when accepted
            .bind(&invite_code)
            .bind(&email)
            .bind(&phone)
            .bind(InviteStatus::Created.as_db_str())
            .bind(expires_at)
            .execute(&mut *tx)
            .await?;

        tx.commit().await?;

        tracing::info!(
            invite_id = %invite_id,
            position_id = %position_id,
            code = %invite_code,
            "Invitation created"
        );

        Ok(PositionInvite {
            id: invite_id,
            position_id,
            invited_by_rep_id,
            candidate_id: None,
            invite_code,
            email,
            phone,
            status: InviteStatus::Created,
            expires_at,
        })
    }

    /// Accept an invitation and establish the candidate-to-organization access relation.
    ///
    /// The invitation code is the public capability for this transition. The
    /// candidate ID is generated by the service, never trusted from a client.
    pub async fn accept_invitation(&self, invite_code: &str) -> Result<Uuid, AppError> {
        // Locking the invitation makes this single-use transition safe under
        // concurrent accept requests while retaining the legacy invite workflow.
        let mut lookup_tx = self.pool.begin().await?;
        let invite_row = sqlx::query(
            "SELECT invitation.id, invitation.position_id, invitation.email, invitation.phone, position.organization_id FROM position_invites invitation JOIN job_positions position ON position.id = invitation.position_id WHERE invitation.invite_code = $1 AND invitation.status IN ('created', 'sent') FOR UPDATE OF invitation"
        )
        .bind(invite_code)
        .fetch_optional(&mut *lookup_tx)
        .await?;

        let invitation = invite_row.ok_or_else(|| {
            AppError::NotFound(format!(
                "Active invitation with code {invite_code} not found"
            ))
        })?;
        let invitation_id: Uuid = invitation.get("id");
        let position_id: Uuid = invitation.get("position_id");
        let organization_id: Uuid = invitation.get("organization_id");
        let email: Option<String> = invitation.get("email");
        let phone: Option<String> = invitation.get("phone");

        // The same transaction owns the row lock and tenant context. Setting the
        // context after deriving the organization keeps the public invite-code
        // boundary separate from tenant-scoped persistence.
        set_transaction_org_context(&mut lookup_tx, organization_id).await?;
        let candidate_id = Uuid::new_v4();

        sqlx::query(
            "INSERT INTO candidates (id, email, phone, analysis_status) VALUES ($1, $2, $3, 'registered')"
        )
        .bind(candidate_id)
        .bind(&email)
        .bind(&phone)
        .execute(&mut *lookup_tx)
        .await?;

        sqlx::query(
            "INSERT INTO candidate_organization_access (candidate_id, organization_id, first_position_id, first_invite_id) VALUES ($1, $2, $3, $4) ON CONFLICT (candidate_id, organization_id) DO NOTHING"
        )
        .bind(candidate_id)
        .bind(organization_id)
        .bind(position_id)
        .bind(invitation_id)
        .execute(&mut *lookup_tx)
        .await?;

        sqlx::query(
            "UPDATE position_invites SET candidate_id = $1, status = 'accepted', accepted_at = NOW() WHERE id = $2"
        )
        .bind(candidate_id)
        .bind(invitation_id)
        .execute(&mut *lookup_tx)
        .await?;

        lookup_tx.commit().await?;

        tracing::info!(
            candidate_id = %candidate_id,
            organization_id = %organization_id,
            invite_id = %invitation_id,
            "Invitation accepted and candidate organization access established"
        );

        Ok(candidate_id)
    }

    async fn position_organization_id(&self, position_id: Uuid) -> Result<Uuid, AppError> {
        sqlx::query("SELECT organization_id FROM job_positions WHERE id = $1")
            .bind(position_id)
            .fetch_optional(&self.pool)
            .await?
            .map(|row| row.get("organization_id"))
            .ok_or_else(|| AppError::NotFound(format!("Position {position_id} not found")))
    }
}
